### ISSUE TITLE
announcement.py (line 130): NameError: name 'announcement' is not defined

### ISSUE THREAD

**Issue by OMerkel** [OMerkel/Announcement#1]
Session log as follows:

> c:\Python34\python.exe controlannouncement.py
> ControlAnnouncement::updateUser
> ControlAnnouncement::sendMail
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "c:\Python34\lib\tkinter__init__.py", line 1533, in **call**
>     return self.func(*args)
>   File "controlannouncement.py", line 117, in sendMail
>     self.announcement.attach()
>   File "D:\work\ReleaseCandidateTest\announcement.py", line 130, in attach
>     announcement.message.attach(part)
> NameError: name 'announcement' is not defined

**Comment by OMerkel** [comment]
Issue got solved by pull request #2
